### PR TITLE
Add .error to .ifError codemod

### PR DESCRIPTION
**Pull request by platy11**
See avajs/ava#995

### CODE REVIEW

**Comment by platy11** [comment]
@sindresorhus @jamestalmage What happened in the Travis build? (https://travis-ci.org/avajs/ava-codemods/jobs/151768289)

**Comment by platy11** [comment]
My new test didn't seem to run. Any ideas?

**Comment by jfmengels** [comment]
I can't check the problems with the tests into much detail right now, but it only breaks on 0.1X versions of Node, which I'm not sure we want to support anymore anyway.

This lookgs great, thanks @platy11!

**Comment by platy11** [comment]
@sindresorhus Can you have a look at this?

**Comment by sindresorhus** [comment]
Looks great @platy11. Nice work :)

**Pull request merged**
